### PR TITLE
Draft Mines Permit OCA Bundle

### PR DESCRIPTION
**Pull request by swcurran**
Here is a draft of the Mines Permit Branch.  In looking at it, I wondered:

- The data elements are all flagged as "PII" -- I'm guessing that is not correct, and that they should be "Not PII".  Perhaps a misunderstanding of what the flag meant?
- I notice that the images for the permit in the Branding JSON reference the "person" credential. Is that expected?  It might well be, since it is a "Government of BC" credential, but I wanted to be sure.

Happy to merge once these questions are answered.

FYI: @Jsyro 

Thanks!

### CODE REVIEW

**Comment by swcurran** [comment]
Not sure the one you were using originally, but if you were using the Person credential, it would make sense that they would be PII, since… “Person” :-) .  If another one — I’d question that.  But should definitely be off in this one.

I’ll make that change.

Re: the shared images.  I’ll make copies of the images for now, and reference local copies.  I agree, there should be a common set that are used, and on the next round, we can do that.

I’ll have that done in a moment.

**Comment by swcurran** [comment]
I notice in the Excel file that the Issuer and Issuer description and Issuer URL are missing. Are there not values we could use for those?

**Comment by swcurran** [comment]
We'll go ahead without the extra issuer data and add it later.

**Comment by amanji** [comment]
@Jsyro There are some examples that may have also incorrectly added flagged attributes that are not considered PII.

**Review by amanji — APPROVED** [review]

**Pull request merged**
