### PR TITLE
feat: updated the production showcase student card

### PR DESCRIPTION
**Pull request by wadeking98**
Bumped the student showcase schema version to 1.4 to match the showcase prod environment

### CODE REVIEW

**Review by amanji — COMMENTED** [review]
Do we need to run anything to update the checksum?

**Comment by amanji** [comment]
LGTM. I'll wait for @swcurran to approve.

**Review by swcurran — APPROVED** [review]

**Review by swcurran — CHANGES_REQUESTED** [review]
You have to update the version in the source document. This is a generated file.

**Comment by swcurran** [comment]
You have to update this file: OCABundles/schema/bcgov-digital-trust/student-card/README.md to change the version.

These files will be deleted soon, and the only version available will be the ones on GitHub pages that are automatically generated from the source.  

BC Wallet needs to address this issue: https://github.com/bcgov/bc-wallet-mobile/issues/1878

**Review by swcurran — APPROVED** [review]

**Pull request merged**
