### PR TITLE
Mines Act Permit first draft

### PR DESCRIPTION
**Pull request by bblazicevic**
Trying to create an OCA bundle for Mines Act Permit issued by the Chief Permitting Officer for Mines using Mines Digital Services.

### CODE REVIEW

**Comment by swcurran** [comment]
This repo requires that DCO (DCO - Developer Certificate of Origin - https://github.com/apps/dco) be used. Please follow the instructions in the failed DCO test "[Details](https://github.com/bcgov/aries-oca-bundles/pull/85/checks?check_run_id=17651601098)" for how to fix the issue.

**Comment by Jsyro** [comment]
@swcurran I'm not sure why this PR was closed, I don't think i did that intentionally. I just force-pushed to comply with the DCO signoff. 

Please reopen and review.

**Comment by swcurran** [comment]
Just to confirm — it is ready for review?  It was in draft before I hit the button...

**Comment by Jsyro** [comment]
Apologies, it should be in draft I suppose. I'm looking at the readme instructions that convert the .xlsx file into the final .json file. Unless that is done magically in the repo, i need to do that still.

**Comment by swcurran** [comment]
Replaced with #86 to expediate the process.

**Pull request closed without merging**
