### PR TITLE
Added new credential definition identifiers for LCRB showcase credentials

### PR DESCRIPTION
**Pull request by andy-credivera**
Added new credential definition identifiers for LCRB showcase credentials

### CODE REVIEW

**Review by swcurran — APPROVED** [review]
It looks to me like the OCA Bundles JSON files were not autogenerated, as I get the files slightly differently — but the content is the same.  Am I right, or is the shell script not determinstic on different platforms?

We’re soon going to be eliminating the use of the JSON files in the repo — and use those that are generated by GHAs that are published on the Git Hub Pages.

**Comment by andy-credivera** [comment]
The gen_ocabundlesjson.sh script was used, but the resulting files needed some manual manipulations afterwards.  For example, here is the end of the list file generated by the script:

```
{ "id": "QEquAHkM35w4XVT3Ku5yat:2:student_card:1.4", "org": "Digital Trust, Government of British Columbia
", "name": "BC Best College Demo Student Card
", "desc": "A verifiable credential schema for a Student Card used in a demo that is part of the BC Gov Digital Trust Showcase.
", "type": "schema", "ocabundle": "OCABundles/schema/bcgov-digital-trust/student-card/OCABundle.json", "shasum": "e65625acad0f1baab8e05b6cd1a5619b22e1f20cb47768616680a0fb2e8dc21d" },
{ "id": "YXCtXE4YhVjULgj5hrk4ML:2:unverified_person:0.1.0", "org": "Digital Trust, Government of British Columbia
", "name": "Unverified Person Credential
", "desc": "A verifiable credential schema for an \"unverified\" person, used in various BC Wallet demos where an unofficial Person credential is useful.
", "type": "schema", "ocabundle": "OCABundles/schema/bcgov-digital-trust/unverified-person/OCABundle.json", "shasum": "48b20b00cb38bed85b9615674d9af32b0d5e16f75e365c144218dad6ec2b7aa0" },
{ "id": "Ep31SvFAetugFPe5CGzJxt:2:Attestation~numérique~d'identité~gouvernemental~(EXP):1.0", "org": "MCN, Government of Quebec
", "name": "QC ANIG ID
", "desc": "A verifiable credential schema used for demonstration and internal use purposes only.
", "type": "schema", "ocabundle": "OCABundles/schema/qc_anig_demo/Attestation_numВrique_didentitВ_gouvernemental/OCABundle.json", "shasum": "29bf8f8729f235450980d0b273f9ca49b7ab73b7358467bf52b311bf40464bb0" }
]
```

Notice all the newlines and the `é` character in the path is replaced with `В`

**Comment by swcurran** [comment]
When I ran the script, the only difference was the ordering.  The new records were at the top of the file instead of after the first two records.

I’m guessing the issue is the Unix environment on which you were running it. What platform were you on when you ran the script?

I’m trying to get us to move over to use GitHub Actions to generate the file, so they are never in the PRs. The raw data is provided, but the GHA generates the file.  That is demonstrated here:

https://bcgov.github.io/aries-oca-bundles/ocabundles.json

That is on a gh-pages site, and SHOULD be the source of the data by a wallet, vs. the files in the repository. As of now, the BC Wallet is (AFAIK — @wadeking98 ) still pulling the data from the GitHub repo.  This issue https://github.com/bcgov/bc-wallet-mobile/issues/1878 is there to make that change.

@andy-credivera — I assume you would prefer that solution vs. having to generate the files and include them in the repo?

@amanji — does the OCA Explorer use the gh-pages version of the files, or is it still pulling from the GitHub repo versions?

**Comment by amanji** [comment]
It now uses the gh-pages version of the file.

**Comment by andy-credivera** [comment]
It would make things easier not having to generate the files as part of the PR, although it is not difficult.  
I think the main benefits of having the GitHub Actions generate it is assurance that the files are properly generated and for new contributors who would be unaware that the script needs to be run as there is no mention of needing to run the script anywhere.

**Pull request merged**
