### PR TITLE
LTSA Demo credential OCA bundle added

### PR DESCRIPTION
**Pull request by arbordeleau**
LTSA Demo credential OCA bundle created by Northern Block.

### CODE REVIEW

**Comment by swcurran** [comment]
Hi @arbordeleau — thanks for putting in the PR.  The proper flow in this repo is that the Excel file that is the source of the OCA data is included in the checkin, so that we can use that to generate/verify the contents of the OCA Bundle, and so that the identifiers in the Overlays are calculated.

- Have you created an Excel file for this batch? 
  - If so, please include it in the PR so that we can verify the bundle was properly generated.
  - If not, please create one as [documented here](https://bcgov.github.io/aries-oca-bundles/contributing/OCABundleCreation/#oca-excel-file)

I now see that the documentation site says that the OCA Excel file is optional, but that should not be the case, and I’ll update. I apologies if that is why you didn’t create/include the Excel file.

**Comment by swcurran** [comment]
I also see that the DCO did not get used.  This repo requires that all commits are signed with DCO.

Please see DCO - Developer Certificate of Origin - https://github.com/apps/dco. To fix, see: https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md and the “details” beside the failed check above.

**Comment by arbordeleau** [comment]
I have used DCO to signed the commit. I also added the missing excel file. 

Thank you!

**Comment by swcurran** [comment]
DCO looks good, but I’m still not seeing the Excel file.

I also don’t think the location of the folder is right.  At minimum, “ltsa-demo” should be “LTSA”, but I also think it should be under the “BCGov” folder — I’m checking the @krobinsonca on that.  I don’t know what “NewCred” means, but the folder title should be named for the type of credential it will be in production.  Below that, you could have a folder “demo” that is used for this early version.

So: schema/bcgov-digital-trust/LTSA/NewCred/demo/

I’m trying to learn more from Kyle to get a better view on the title and location of the folder.

**Comment by arbordeleau** [comment]
Sorry, the Excel file was supposed to be included. I have also updated the folder structure as per your recommendation, thank you! Additionally, 'NewCred Credential' is the credential name LTSA has chosen for the demo, so I understand why it may have seemed unclear.

**Comment by swcurran** [comment]
Looking good, but not quite there yet.

First, the OCABundle.json file needs to be generated from the Excel. I generated it, and it is quite different from what you have in the PR.  To generate it, you have to have the software to run the script, which is a bit of pain.  We’re working on making this a “post-PR merge” step, but BC Wallet doesn’t yet support that, so it has to be done as part of the merge. The script is to be run from is `scripts/genBundle.sh` in the repo, run from the `demo` folder with arguments `-x OCA.xlsx branding.json`.  It’s a pain...

Second, another script needs to be run from the root of the repo `./scripts/gen_ocabundlesjson.sh`. It generates a couple of other files in the root.

If that is not easy for you to set up, I would suggest that you remove the `OCABundle.json` from the `demo` folder, and then I’ll do a PR to put the two steps above.  Let me know — happy to do that.

Sorry this is such a pain.

**Comment by arbordeleau** [comment]
Thanks for the clarification! 

I'll gladly take your help with running the necessary scripts. I've removed the OCABundle.json file from the demo folder and pushed the changes. 

Thanks again for assisting with this! Looking forward to your PR with the steps.

**Review by swcurran — APPROVED** [review]

**Comment by arbordeleau** [comment]
Thank you for the quick response and push! I was testing on the BC Wallet, and I noticed that the issuer logo is missing. Could you please confirm if this is something on my end or if it’s related to the recent changes? Appreciate your help in clarifying. Do i needed to add it on the excel file as well? I remember only included it in the branding.json and in png in the folder /demo.

**Comment by swcurran** [comment]
Ah…I see.  The path in the branding.json file did not get changed when the folder location was changed.  I’ll update...

**Pull request merged**
